### ISSUE TITLE
`RCBlockNumberProviderOf` returns different values for relay chain block number if the parachain is spawned from chainspec or via rpc node

### ISSUE THREAD

**Issue by tdimitrov** [AcalaNetwork/chopsticks#823]
Noticed a strange behaviour when testing a runtime migration with chopsticks.

I was testing the runtime upgrade enabling coretime on Polkadot. It involves sending of XCM messages from Polkadot relay chain to Coretime relay chain.

One particular message is `SetLease` which is handled [here](https://github.com/paritytech/polkadot-sdk/blob/5a431470d2a4155a4bb00ea6ac07d7f9707f8e82/substrate/frame/broker/src/dispatchable_impls.rs#L65). Note the `ensure` line which compares `until` with `Self::current_timeslice()` which is implemented [here](https://github.com/paritytech/polkadot-sdk/blob/08498f5473351c3d2f8eacbe1bfd7bc6d3a2ef8d/substrate/frame/broker/src/utility_impls.rs#L35). `let latest = RCBlockNumberProviderOf::<T::Coretime>::current_block_number();` is supposed to fetch the current block number of the relay chain.

At this point I get different values for `current_block_number` depending on if I run the coretime chain from a chainspec or against an actual RPC node. In the former case I get `1004` while at the latter - `22572435`. In both cases the relay chain configuration of chopsticks has `block: 22572434` so I expect in both cases `current_timeslice()` to return `22572435` (one block after the runtime upgrade.

Is there a reason for this behaviour which I don't see?

# How to recreate
Recreating the issue is a bit tedious because it requires modified coretime runtime with `sp-debug-derive` enabled and an additional trace line [here](https://github.com/paritytech/polkadot-sdk/blob/08498f5473351c3d2f8eacbe1bfd7bc6d3a2ef8d/substrate/frame/broker/src/utility_impls.rs#L36).

I've prepared a docker-compose setup here -> https://github.com/tdimitrov/polkadot-coretime-launch-test/tree/post-migration

I'll attach the two binaries (relay chain wasm with the coretime migration and modified coretime wasm) to the issue.

**Comment by tdimitrov** [comment]
[artefacts.zip](https://github.com/user-attachments/files/17114024/artefacts.zip)

**Comment by xlc** [comment]
Not sure what's the best way to solve this but here is what happened:

When creating the validation data inherent, Chopsticks will try to fetch the parent one and use it as the starting point. So it kinda works for chain with RPC endpoint.

However, when created from chain spec file, there is no parent block, so a hardcoded one is used: https://github.com/AcalaNetwork/chopsticks/blob/29e5a78cc20ddd1a1edae4a1c28c8888a6e03b61/packages/core/src/blockchain/inherent/parachain/validation-data.ts#L23-L25

and then the relaychain block number value is incremented https://github.com/AcalaNetwork/chopsticks/blob/29e5a78cc20ddd1a1edae4a1c28c8888a6e03b61/packages/core/src/blockchain/inherent/parachain/validation-data.ts#L290

The thing is, for Chopsticks, every chain are independent. Even if they are connected via XCM, Chopsticks only forward the messages to the other chain. But the validation data are not actually using the value from relaychain (because in many cases, there is no relaychain being simulated).

**Comment by tdimitrov** [comment]
I see, thanks @xlc 

> So it kinda works for chain with RPC endpoint.

Can you elaborate on this? Why 'kinda works'? Any potential pitfalls one needs to know about?

**Comment by xlc** [comment]
for RPC networks, the parent block will be a real block that contains real relaychain block height. if both relaychain and parachain are using rpc endpoints with latest block, it will work as expected

**Comment by xlc** [comment]
One thing we could do is add a new parameter to `dev_newBlock` to specify the relaychain block height to give you more control of it

**Comment by tdimitrov** [comment]
> One thing we could do is add a new parameter to dev_newBlock to specify the relaychain block height to give you more control of it

This will be useful but probably easy to look over. Do you see a benefit in making it a required parameter if a chain is spawned from a chainspec?

**Comment by xlc** [comment]
it is not used most of the time so no it shouldn't be a required parameter

**Comment by tdimitrov** [comment]
I agree it's not used most of the time, but if not used it might yield unexpected data which might bite the user badly.

Bottom line it's up to you. Being able to override this value is more than fine for me.
