### ISSUE TITLE
PAPI storage getEntries() returns only 100 entries

### ISSUE THREAD

**Issue by 0xKheops** [AcalaNetwork/chopsticks#837]
Hi,

First of all thank you for providing us with this great tool! 

While trying to run my polkadot-api (PAPI) based dapp on chopsticks I noticed that on Asset Hub, `api.query.Assets.Metadata.getEntries()` returns only the first 100 items, instead of 300+

I noticed that it can be fixed by wrapping the provider with `withPolkadotSdkCompat`, but I've been told that it shouldn't be necessary.

Repo to reproduce : https://github.com/0xKheops/papi-chopsticks-getentries

I get this output:
![image](https://github.com/user-attachments/assets/a5846af3-e00b-4c08-91a3-2e3f46e50e84)

**Comment by xlc** [comment]
https://github.com/AcalaNetwork/chopsticks/blob/5847a27a447f716a5df07215d80bb3dc673ec825/packages/core/src/rpc/rpc-spec/chainHead_v1.ts#L208 it is not yet completed

@voliva do you want to finish this? otherwise I can work on it next week.

**Comment by voliva** [comment]
I'll take a look - this TODO it's not exactly it, what this TODO is refering to is exposing pagination the way the new spec supports it: Through the `operationWaitingForContinue` and `chainHead_v1_continue`.

But the current implementation is supposed to run the whole storage list without doing this pagination, so it's weird that it stops at the first 100 elements. The relevant lines in this file are `while (startKey)` and `startKey = keys[pageSize - 1] ?? null`.

Now I see it's actually this line:
https://github.com/AcalaNetwork/chopsticks/blob/5847a27a447f716a5df07215d80bb3dc673ec825/packages/core/src/rpc/rpc-spec/chainHead_v1.ts#L232

I probably didn't mean to do that 🤔 otherwise what's the point of the loop?

**Comment by voliva** [comment]
To clarify, I'm implementing operationWaitingForContinue + chainHead_v1_continue. It's something I can get done in the next days 👍
