### ISSUE TITLE
implement `provider.api.rpc.engine.createBlock`

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/chopsticks#91]
not necessary for functionalities, but some bodhi tests use it, so it's a nice to have for bodhi compatibility

**Comment by xlc** [comment]
we have `dev_newBlock` already. I guess we can alias it to be bit more compatible with existing scripts using manual seal

**Comment by DrW3RK** [comment]
I might need help with this - How can I issue the RPC call to fast-forward the chain? I do not see an option on Polkadot-JS UI.  https://github.com/AcalaNetwork/chopsticks/issues/71 ?

**Comment by xlc** [comment]
polkadot.js apps doesn't have good support of custom/known RPC so you will need use some other tool to make the RPC call.

I am currently using Postman but there are many good alternative tools available for making WS RPC calls.

For fast forward, you can do this
```
{
  "id": 2,
    "jsonrpc": "2.0",
    "method": "dev_newBlock",
	"params": [{"count": 10}]
}
```

Note that due to #83 it is still going to take few seconds to build each block

**Comment by ermalkaleci** [comment]
@DrW3RK you can use polkadotjs/app to trigger rpc call like this
<img width="1481" alt="Screenshot 2022-12-17 at 10 13 39 PM" src="https://user-images.githubusercontent.com/3055344/208266588-d3770c58-56dc-4702-a3f4-687f03de5b58.png">
